### ISSUE TITLE
Loading pre-trained wav2vec2.0 model error

### ISSUE THREAD

**Issue by Kristopher-Chen** [nii-yamagishilab/mos-finetune-ssl#1]
Hi, have you encountered the error of loading pre-trained wav2vec2.0 models?  

the code is as follows: 
`  cp_path = './ssl/xlsr_53_56k.pt'
  model, cfg, task = fairseq.checkpoint_utils.load_model_ensemble_and_task([cp_path])
  model = model[0]
  model.eval()`

it works with hubert_large_ll60k.pt, but not with xlsr_53_56k.pt.

the error code is 
`omegaconf.errors.ConfigKeyError: Key 'eval_wer' not in 'AudioPretrainingConfig'
	full_key: eval_wer
	reference_type=Optional[AudioPretrainingConfig]
	object_type=AudioPretrainingConfig`

Thank you!

**Comment by liushenme** [comment]
Hi, I have the same problem. Have you solved it?

**Comment by Kristopher-Chen** [comment]
> Hi, I have the same problem. Have you solved it?

Yes, there is something missing in the defined structure. Copy the missing definitions from fairseq/tasks/audio_fintuning.py to fairseq/tasks/audio_pretraining.py
